on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

name: Main Workflow

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Cache SonarCloud packages
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Analisar com SonarCloud
        uses: SonarSource/sonarcloud-github-action@de2e56b42aa84d0b1c5b622644ac17e505c9a049
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args:
            -Dsonar.projectKey=rafaeldemiranda95_Pedido
            -Dsonar.organization=rafaeldemiranda95
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
            # Descomente e ajuste as linhas abaixo se necessário
            # -Dsonar.sources=src
            # -Dsonar.tests=tests
            # -Dsonar.verbose=true
